<a href="https://colab.research.google.com/github/MohamedTolba1199/Natural_Language_Processing/blob/main/NLP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#POS(Part of speech)

1- token.pos_ >>>>>>>represent pos(verp, noun,....)

2- spacy.explain(token.pos_)   >>>>>akes the part-of-speech tag as an argument and returns a brief explanation of what the pos represents.

3- token.tag_  >>>> tell me the tense(الزمن  بتاعى )

4- spacy.explain(token.tag_ ) >>>> returns a brief explanation of what the tag represents

In [1]:
import spacy
!python -m spacy download  en_core_web_sm

# en_core_web_sm  >>>>>> pre-trained model is designed for processing English text for tasks such as
# part-of-speech tagging, named entity recognition, and dependency parsing.

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 33.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [2]:
nlp=spacy.load("en_core_web_sm")
doc=nlp("Elon flew to mars yesterday. He carried biryani masala with him")
for token in doc:
  #print(token , token.pos_)
  print(token ,'|', token.pos_ ,'|',spacy.explain(token.pos_))

Elon | PROPN | proper noun
flew | VERB | verb
to | ADP | adposition
mars | NOUN | noun
yesterday | NOUN | noun
. | PUNCT | punctuation
He | PRON | pronoun
carried | VERB | verb
biryani | ADJ | adjective
masala | NOUN | noun
with | ADP | adposition
him | PRON | pronoun


In [3]:
doc = nlp("Wow! Dr. Strange made 265 million $ on the very first day")

for token in doc:
    print(token," || ", token.pos_, " || ", spacy.explain(token.pos_), " || ", token.tag_, " || ", spacy.explain(token.tag_))

Wow  ||  INTJ  ||  interjection  ||  UH  ||  interjection
!  ||  PUNCT  ||  punctuation  ||  .  ||  punctuation mark, sentence closer
Dr.  ||  PROPN  ||  proper noun  ||  NNP  ||  noun, proper singular
Strange  ||  PROPN  ||  proper noun  ||  NNP  ||  noun, proper singular
made  ||  VERB  ||  verb  ||  VBD  ||  verb, past tense
265  ||  NUM  ||  numeral  ||  CD  ||  cardinal number
million  ||  NUM  ||  numeral  ||  CD  ||  cardinal number
$  ||  NUM  ||  numeral  ||  CD  ||  cardinal number
on  ||  ADP  ||  adposition  ||  IN  ||  conjunction, subordinating or preposition
the  ||  DET  ||  determiner  ||  DT  ||  determiner
very  ||  ADV  ||  adverb  ||  RB  ||  adverb
first  ||  ADJ  ||  adjective  ||  JJ  ||  adjective (English), other noun-modifier (Chinese)
day  ||  NOUN  ||  noun  ||  NN  ||  noun, singular or mass


##Using pos as a filter for Removing all SPACE, PUNCT and X token from text

In [4]:
earnings_text="""Microsoft Corp. today announced the following results for the quarter ended December 31, 2021, as compared to the corresponding period of last fiscal year:

·         Revenue was $51.7 billion and increased 20%
·         Operating income was $22.2 billion and increased 24%
·         Net income was $18.8 billion and increased 21%
·         Diluted earnings per share was $2.48 and increased 22%
“Digital technology is the most malleable resource at the world’s disposal to overcome constraints and reimagine everyday work and life,” said Satya Nadella, chairman and chief executive officer of Microsoft. “As tech as a percentage of global GDP continues to increase, we are innovating and investing across diverse and growing markets, with a common underlying technology stack and an operating model that reinforces a common strategy, culture, and sense of purpose.”
“Solid commercial execution, represented by strong bookings growth driven by long-term Azure commitments, increased Microsoft Cloud revenue to $22.1 billion, up 32% year over year” said Amy Hood, executive vice president and chief financial officer of Microsoft."""

nlp=spacy.load("en_core_web_sm")
doc=nlp(earnings_text)

filtered_tokens=[]
for token in doc:
  if token.pos_ not in ["SPACE","PUNCT","X"]:
    filtered_tokens.append(token)

In [5]:
filtered_tokens[:10]

[Microsoft,
 Corp.,
 today,
 announced,
 the,
 following,
 results,
 for,
 the,
 quarter]

##get the count of each pos

In [6]:
count=doc.count_by(spacy.attrs.POS)
count

{96: 13,
 92: 46,
 100: 24,
 90: 9,
 85: 16,
 93: 16,
 97: 27,
 98: 1,
 84: 20,
 103: 10,
 87: 6,
 99: 5,
 89: 12,
 86: 3,
 94: 3,
 95: 2}

In [7]:
doc.vocab[96].text

'PROPN'

In [8]:
count.items()
for k,v in count.items():
  print(doc.vocab[k].text,'|',v)


PROPN | 13
NOUN | 46
VERB | 24
DET | 9
ADP | 16
NUM | 16
PUNCT | 27
SCONJ | 1
ADJ | 20
SPACE | 10
AUX | 6
SYM | 5
CCONJ | 12
ADV | 3
PART | 3
PRON | 2


##apply pos using ntlk not spacy

In [9]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
text = "The quick brown fox jumps over the lazy dog."
# Tokenize the text into individual words
words = nltk.word_tokenize(text)

# Perform POS tagging on the tokenized words
pos_tags = nltk.pos_tag(words)

# Print the POS tags for each word
for word, tag in pos_tags:
    print(word, tag)

The DT
quick JJ
brown NN
fox NN
jumps VBZ
over IN
the DT
lazy JJ
dog NN
. .


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


#Named Entity Recognition

In [10]:
import spacy
nlp = spacy.load("en_core_web_sm")

# en_core_web_sm >>> small model
# en_core_web_md >>> meduim model
# en_core_web_lg >>> large model

In [11]:
nlp.pipe_names
#the tasks which it will do

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [12]:
doc1 = nlp("Tesla Inc is going to acquire twitter for $45 billion")

for ent in doc.ents:
    print(ent.text, " | ", ent.label_, " | ", spacy.explain(ent.label_))

Microsoft Corp.  |  ORG  |  Companies, agencies, institutions, etc.
today  |  DATE  |  Absolute or relative dates or periods
the quarter ended December 31, 2021  |  DATE  |  Absolute or relative dates or periods
last fiscal year  |  DATE  |  Absolute or relative dates or periods
$51.7 billion  |  MONEY  |  Monetary values, including unit
20%  |  PERCENT  |  Percentage, including "%"
$22.2 billion  |  MONEY  |  Monetary values, including unit
24%  |  PERCENT  |  Percentage, including "%"
$18.8 billion  |  MONEY  |  Monetary values, including unit
21%  |  PERCENT  |  Percentage, including "%"
2.48  |  MONEY  |  Monetary values, including unit
22%  |  PERCENT  |  Percentage, including "%"
Digital  |  ORG  |  Companies, agencies, institutions, etc.
Satya Nadella  |  PERSON  |  People, including fictional
Microsoft  |  ORG  |  Companies, agencies, institutions, etc.
Microsoft  |  ORG  |  Companies, agencies, institutions, etc.
$22.1 billion  |  MONEY  |  Monetary values, including unit
32% 

In [13]:
from spacy import displacy

displacy.render(doc1,style='ent')
# https://onecompiler.com/html/3zec3j8sc  >>> to show the result

'<div class="entities" style="line-height: 2.5; direction: ltr">\n<mark class="entity" style="background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    Tesla Inc\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">ORG</span>\n</mark>\n is going to acquire twitter for \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    $45 billion\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">MONEY</span>\n</mark>\n</div>'

In [14]:
##List down all the entities
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [15]:
doc = nlp("Tesla Inc is going to acquire Twitter Inc for $45 billion")
for ent in doc.ents:
    print(ent.text, " | ", ent.label_, " | ", ent.start_char, "|", ent.end_char)

Tesla Inc  |  ORG  |  0 | 9
Twitter Inc  |  ORG  |  30 | 41
$45 billion  |  MONEY  |  46 | 57


In [16]:
#Setting custom entities
doc = nlp("Tesla is going to acquire Twitter for $45 billion")
for ent in doc.ents:
    print(ent.text, " | ", ent.label_)


#here, when we deleted inc after twitter, the result was twiiter is product and that uncorrect so i need to handle in manually

Tesla  |  ORG
Twitter  |  PRODUCT
$45 billion  |  MONEY


In [17]:
s = doc1[2:5]
s

is going to

In [18]:
type(s)

spacy.tokens.span.Span

In [19]:
from spacy.tokens import Span
s1=Span(doc,0,1,label="ORG")
s2=Span(doc,5,6,label="ORG")

doc.set_ents([s1,s2],default="unmodified")
# save the changes in s1,s2 without modification in others indices

for ent in doc.ents:
  #print(ent.text , "|" , ent.label)
  print(ent.text , "|" , ent.label_)

Tesla | ORG
Twitter | ORG
$45 billion | MONEY


##using NLTK


1- ne_chunk >>> responsible for NER IN NLTK which take tags as an input

In [20]:
import nltk
nltk.download('maxent_ne_chunker')
nltk.download('words')
from nltk import word_tokenize, pos_tag, ne_chunk

# Define input text
input_text = "Steve Jobs was the CEO of Apple Corp. in California."

# Tokenize input text
tokens = word_tokenize(input_text)

# Perform Part-of-Speech (POS) tagging
pos_tags = pos_tag(tokens)
print('-'*100)
print('pos_tags',pos_tags)
print('-'*100)

# Perform Named Entity Recognition (NER)
ne_tree = ne_chunk(pos_tags)
print('ne_tree',ne_tree)

----------------------------------------------------------------------------------------------------
pos_tags [('Steve', 'NNP'), ('Jobs', 'NNP'), ('was', 'VBD'), ('the', 'DT'), ('CEO', 'NNP'), ('of', 'IN'), ('Apple', 'NNP'), ('Corp.', 'NNP'), ('in', 'IN'), ('California', 'NNP'), ('.', '.')]
----------------------------------------------------------------------------------------------------
ne_tree (S
  (PERSON Steve/NNP)
  (PERSON Jobs/NNP)
  was/VBD
  the/DT
  (ORGANIZATION CEO/NNP)
  of/IN
  (ORGANIZATION Apple/NNP Corp./NNP)
  in/IN
  (GPE California/NNP)
  ./.)


[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


#spell correction

1- using spellchecker()

2- using textblob()

In [21]:
from textblob import TextBlob

# Create a TextBlob object with the text to correct
text = "I havv a goood speling!"



In [22]:
# Create a new TextBlob object with corrected spelling
correct_text = TextBlob(text).correct()
print(correct_text)


I have a good spelling!


# Bag of words (BOW):

In [23]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [24]:
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [25]:
stemmer = PorterStemmer()
lemitizer = WordNetLemmatizer()

sentence = nltk.sent_tokenize(paragraph)
sentence

['I have three visions for India.',
 'In 3000 years of our history, people from all over\n               the world have come and invaded us, captured our lands, conquered our minds.',
 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.',
 'Yet we have not done this to any other nation.',
 'We have not conquered anyone.',
 'We have not grabbed their land, their culture,\n               their history and tried to enforce our way of life on them.',
 'Why?',
 'Because we respect the freedom of others.That is why my\n               first vision is that of freedom.',
 'I believe that India got its first vision of\n               this in 1857, when we started the War of Independence.',
 'It is this freedom that\n               we must protect and nurture and build on.',
 'If we are not free, no one will respect us.',
 'My second vision for India’s development.'

In [26]:
corpus = []

for i in range(len(sentence)):
  review=re.sub("[^a-zA-Z]",' ',sentence[i])
  review=review.lower()
  review=review.split()
  #review=[stemmer.stem(word) for word in review if not word in stopwords.words('english')]
  review=[lemitizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [27]:
corpus

['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
data = bow.fit_transform(corpus).toarray()
data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
data.shape

(31, 114)

#N-GRAM

##Uni-GRAM

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

# give each word individually and it's index as a column
# by default(one gram)
# using fit function not fit_transform

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

In [31]:
v = CountVectorizer(ngram_range=(1,1))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

##BI-GRAM

In [32]:
text =["Thor Hathodawala is looking for a job"]
bow = CountVectorizer(ngram_range=(1,2))
bow.fit(text)
bow.vocabulary_

{'thor': 9,
 'hathodawala': 2,
 'is': 4,
 'looking': 7,
 'for': 0,
 'job': 6,
 'thor hathodawala': 10,
 'hathodawala is': 3,
 'is looking': 5,
 'looking for': 8,
 'for job': 1}

In [33]:
bow = CountVectorizer(ngram_range=(1,3))
bow.fit(text)
bow.vocabulary_

{'thor': 12,
 'hathodawala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodawala': 13,
 'hathodawala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodawala is': 14,
 'hathodawala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

##Task :

1- remove stop words

2- lemmatize the text

3- apply n-gram

In [34]:
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [35]:
# load english language model
nlp = spacy.load("en_core_web_sm")
def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)


In [36]:
preprocess("Thor ate pizza")

'thor eat pizza'

In [37]:
preprocess("Loki is eating pizza")

'Loki eat pizza'

In [38]:
data = [preprocess(text) for text in corpus]
data

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [39]:
bi_gram= CountVectorizer(ngram_range=(1,2))
bi_gram.fit(data)
bi_gram.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [40]:
# fit >>>> take all the documents.
# transform  >>> take sentence that you want to encode it.
bi_gram.transform(["Thor eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]])

In [41]:
bi_gram.transform(["Hulk eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0, 0]])

#TF-IDF

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [43]:
# Example documents
docs = [
  "The quick brown fox jumps over the lazy dog.",
  "A stitch in time saves nine.",
  "The early bird catches the worm.",
  "Actions speak louder than words.",
]

In [44]:
tf_idf=TfidfVectorizer()
tf_data=tf_idf.fit_transform(docs).toarray()
tf_data

array([[0.        , 0.        , 0.32467583, 0.        , 0.32467583,
        0.        , 0.32467583, 0.        , 0.32467583, 0.32467583,
        0.        , 0.        , 0.32467583, 0.32467583, 0.        ,
        0.        , 0.        , 0.        , 0.5119563 , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4472136 , 0.        , 0.        ,
        0.        , 0.4472136 , 0.        , 0.        , 0.4472136 ,
        0.        , 0.4472136 , 0.        , 0.        , 0.4472136 ,
        0.        , 0.        ],
       [0.        , 0.39264414, 0.        , 0.39264414, 0.        ,
        0.39264414, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.6191303 , 0.        ,
        0.        , 0.39264414],
       [0.4472136 , 0.        , 0.        , 0.        , 0.        ,
        0.       

When sklearn.__version__ <= 0.24.x use following method

get_feature_names()


When sklearn.__version__ >= 1.0.x use following method

get_feature_names_out()

In [45]:
pd.DataFrame(tf_data , columns=tf_idf.get_feature_names_out())
# will make every unique word as a feature, so because I have 22 columns.
# noticed, the most frequency word is the least value of TF-IDF

actions      bird     brown   catches       dog     early       fox  \
0  0.000000  0.000000  0.324676  0.000000  0.324676  0.000000  0.324676   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.392644  0.000000  0.392644  0.000000  0.392644  0.000000   
3  0.447214  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         in     jumps      lazy  ...      over     quick     saves     speak  \
0  0.000000  0.324676  0.324676  ...  0.324676  0.324676  0.000000  0.000000   
1  0.447214  0.000000  0.000000  ...  0.000000  0.000000  0.447214  0.000000   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.447214   

     stitch      than       the      time     words      worm  
0  0.000000  0.000000  0.511956  0.000000  0.000000  0.000000  
1  0.447214  0.000000  0.000000  0.447214  0.000000  0.000000  
2  0.000000  0.000000  0.619130  0.000000  0.000000  0.392644  
3  0.000000  0.447214  0.000000  0.000000  0.447214  0.000000  

[4 rows x 22 columns]

## the numbers of uniques words(min_df)

1- min_df>>>>>>> will control the numbers of words which will be appeared based on numbers of frequency

In [46]:
#the default of min_df is one
doc1 = "the quick brown fox"
doc2 = "the lazy dog"
doc3 = "the quick brown cat"

tf_idf = TfidfVectorizer(min_df=2)
Data = tf_idf.fit_transform([doc1, doc2, doc3])
print(tf_idf.get_feature_names_out())  # ['brown', 'cat', 'dog', 'fox', 'lazy', 'quick', 'the']
print(Data.toarray())

['brown' 'quick' 'the']
[[0.61980538 0.61980538 0.48133417]
 [0.         0.         1.        ]
 [0.61980538 0.61980538 0.48133417]]


In [47]:
tf_idf = TfidfVectorizer(min_df=2,stop_words='english')
Data= tf_idf.fit_transform([doc1, doc2, doc3])
print(tf_idf.get_feature_names_out())  # ['brown', 'quick', 'the']
print(Data.toarray())

#noticed that [the]>>>>>>>>not appeared becuse it is from stop_word

['brown' 'quick']
[[0.70710678 0.70710678]
 [0.         0.        ]
 [0.70710678 0.70710678]]
